services:
  database:
    image: postgres:17.0-alpine
    container_name: url-shortener-db
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app-net

networks:
  app-net:
    driver: bridge